name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.7'

    - name: Clear Go Module Cache
      run: go clean -modcache

    - name: Install dependencies
      run: |
        go get github.com/lib/pq
        go get github.com/gorilla/mux

    - name: Tidy and install modules
      run: go mod tidy

    - name: Build
      run: go build -v ./...

    - name: Run Tests with Race Detection and Coverage
      run: |
        go test -race -v -coverprofile=coverage.out ./...
        go tool cover -func=coverage.out
